version: '3.8'
services:
  web:
    image: openjdk:21-oracle
    container_name: springnewbie-app
    environment:
      SPRING_DATASOURCE_URL: /path/to/database
      SPRING_DATASOURCE_USERNAME: fill it
      SPRING_DATASOURCE_PASSWORD: fill it
    volumes:
      - ./target/app.jar:/app/app.jar
    command: ["java", "-jar", "/app/app.jar"]
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: fill it
      MYSQL_DATABASE: fill it
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: